{
  "comments": [
    {
      "key": {
        "uuid": "5a43c5e1_ddb94bee",
        "filename": "managesf/model/yamlbkd/resources/group.py",
        "patchSetId": 2
      },
      "lineNbr": 120,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "The previous gerrit client of pysflib returned false in case of 404/409. So after the gerrit bump patch pass we absolutely need to fix all of that in resources ops.",
      "range": {
        "startLine": 119,
        "startChar": 0,
        "endLine": 120,
        "endChar": 74
      },
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_1d581356",
        "filename": "managesf/model/yamlbkd/resources/group.py",
        "patchSetId": 2
      },
      "lineNbr": 120,
      "author": {
        "id": 7
      },
      "writtenOn": "2018-04-05T04:44:58Z",
      "side": 1,
      "message": "Indeed",
      "parentUuid": "5a43c5e1_ddb94bee",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_3d170fef",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 59,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "A log warning could be convenient here.",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_9d6c230a",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 59,
      "author": {
        "id": 7
      },
      "writtenOn": "2018-04-05T04:43:35Z",
      "side": 1,
      "message": "This method is attempted everytime the admin logs in, or when automated api calls, so we should silent this as it will report false-alarm.",
      "parentUuid": "5a43c5e1_3d170fef",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_9ddc2348",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 70,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "Should be first line of the method imo",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_bd71dfe2",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 70,
      "author": {
        "id": 7
      },
      "writtenOn": "2018-04-05T04:43:35Z",
      "side": 1,
      "message": "We should do it after the cauth_id \u003d\u003d 1 check as per my above comment.",
      "parentUuid": "5a43c5e1_9ddc2348",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_1d1a5318",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 75,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "You can remove the try/except here as the if line 73 will make sure you have at least one value in the array.",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_5d777bd4",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 75,
      "author": {
        "id": 7
      },
      "writtenOn": "2018-04-05T04:43:35Z",
      "side": 1,
      "message": "ok",
      "parentUuid": "5a43c5e1_1d1a5318",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_fdd76721",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 99,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "We should probably raise in _add_account_as_external line 56 as if we fail define it in the table the account we be partially created.",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_7d74b7ce",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 99,
      "author": {
        "id": 7
      },
      "writtenOn": "2018-04-05T04:43:35Z",
      "side": 1,
      "message": "This won\u0027t work because the sf_users table won\u0027t be populated. Then further connection will not reach that part because the account creation will fail with 409. Perhaps the external id insertion should be attempted in the update method too?",
      "parentUuid": "5a43c5e1_fdd76721",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_bde1df00",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 119,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "should be first line of the method.",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_5de77b12",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 134,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "Format string to fix and should be first line of the method",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_bd48ff88",
        "filename": "managesf/services/gerrit/user.py",
        "patchSetId": 2
      },
      "lineNbr": 134,
      "author": {
        "id": 7
      },
      "writtenOn": "2018-04-05T04:43:35Z",
      "side": 1,
      "message": "Let\u0027s investigate the method call flow, i worry this will cause too much un-necessary logging.",
      "parentUuid": "5a43c5e1_5de77b12",
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a43c5e1_7de4b70c",
        "filename": "managesf/services/gerrit/utils.py",
        "patchSetId": 2
      },
      "lineNbr": 354,
      "author": {
        "id": 6
      },
      "writtenOn": "2018-04-04T13:07:39Z",
      "side": 1,
      "message": "Yes, agree to display data only via GerritClientError and remove this low level logging in that file.",
      "range": {
        "startLine": 354,
        "startChar": 1,
        "endLine": 354,
        "endChar": 66
      },
      "revId": "1e020431bf5ac47a45900c1f0ac1680dd4ded35b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}